---
image: node:alpine
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - ~/.npm
    - .jest
stages:
  - test
  - deploy
before_script:
  - npm ci
expo-deployments:
  stage: deploy
  script:
    - apk add --no-cache bash
    - npx npm install -g expo-cli
    - npx expo login -u 'duythanh3101' -p 'J3hEsu123'
    - npx expo build:android --type app-bundle --non-interactive --no-wait --no-publish