export const globalActionTypes = {
    ACCOUNT_LOGIN: 'ACCOUNT_LOGIN',
    ACCOUNT_LOGOUT : 'ACCOUNT_LOGOUT',
    MAPDATA_ADD_USER: 'MAPDATA_ADD_USER',
    MAPDATA_DELETE: 'MAPDATA_ADD',
    MAPDATA_ADD_PARENTKEY: 'MAPDATA_ADD_PARENTKEY',

};